(function (G) {
  'use strict';
  var A = G.ZWMSH = G.ZWMSH || {}, HOST = 'zwm-social-helper-host', lastUrl = location.href, timer = null, observer = null, toastTimer = null;
  function root() { var h = document.getElementById(HOST); return h && h.shadowRoot; }
  function safe(s) { return (String(s || 'xiaohongshu').replace(/[\\/:*?"<>|]+/g, '_').replace(/\.+$/g, '').trim() || 'xiaohongshu').slice(0, 70); }
  function ext(u, f) { try { var m = new URL(u).pathname.match(/\.(jpe?g|png|webp|avif|gif|mp4|mov|m4v)$/i); return m ? '.' + m[1].toLowerCase().replace('jpeg','jpg') : f; } catch (_) { return f; } }
  function toast(s) { var e = root() && root().getElementById('toast'); if (!e) return; e.textContent = s; e.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(function () { e.classList.remove('show'); }, 1500); }
  function copy(s) { try { if (typeof GM_setClipboard === 'function') GM_setClipboard(String(s || ''), 'text'); else navigator.clipboard.writeText(String(s || '')); toast('已复制'); } catch (_) { toast('复制失败'); } }
  function openUrl(u) { var a = document.createElement('a'); a.href = u; a.target = '_blank'; a.rel = 'noopener noreferrer'; a.click(); }
  function dl(u, name) { if (!u) return; try { if (typeof GM_download === 'function') return GM_download({url:u, name:name, saveAs:false, onerror:function(){openUrl(u);}}); } catch (_) {} openUrl(u); }
  function data() { var d = A.extract ? A.extract() : {}; update(d); return d; }
  function update(d) { var r = root(); if (!r) return; var t = r.getElementById('noteTitle'), m = r.getElementById('noteMeta'); if (t) t.textContent = d.title || d.noteId || '未识别到笔记'; if (m) m.textContent = '作者：' + (d.author && d.author.name || '未知') + ' · 图片 ' + (d.images || []).length + ' · 视频 ' + (d.videos || []).length; }
  function downloadImages() { var d = data(), b = safe(d.title || d.noteId); if (!d.images.length) return toast('没有识别到图片'); d.images.forEach(function(u,i){ setTimeout(function(){ dl(u, b + '-' + String(i+1).padStart(2,'0') + ext(u,'.jpg')); }, i*250); }); toast('开始处理 ' + d.images.length + ' 张图片'); }
  function downloadVideo() { var d = data(), b = safe(d.title || d.noteId); if (!d.videos.length) return toast('没有识别到视频'); d.videos.forEach(function(u,i){ setTimeout(function(){ dl(u, b + (d.videos.length>1?'-'+(i+1):'') + ext(u,'.mp4')); }, i*300); }); toast('开始处理 ' + d.videos.length + ' 个视频'); }

  function ensure() {
    if (document.getElementById(HOST)) return;
    var h = document.createElement('div'); h.id = HOST; document.documentElement.appendChild(h); var s = h.attachShadow({mode:'open'});
    s.innerHTML = '<style>:host{all:initial}*{box-sizing:border-box}.z{position:fixed;right:14px;bottom:calc(82px + env(safe-area-inset-bottom));z-index:2147483647;width:54px;height:54px;border:0;border-radius:18px;background:#111827;color:#fff;font:700 14px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 8px 30px #0004}.p{display:none;position:fixed;z-index:2147483647;right:12px;bottom:calc(146px + env(safe-area-inset-bottom));width:min(360px,calc(100vw - 24px));max-height:min(610px,calc(100vh - 190px));overflow:auto;background:#fffffff8;color:#111827;border:1px solid #0001;border-radius:18px;box-shadow:0 16px 50px #0004;padding:14px;font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.p.open{display:block}.h{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.h b{font-size:16px}.v{font-size:11px;color:#6b7280}.s{padding:10px;border-radius:12px;background:#f3f4f6;margin-bottom:10px;word-break:break-word}.s b{display:block;margin-bottom:4px}.m{font-size:12px;color:#6b7280}.g{display:grid;grid-template-columns:1fr 1fr;gap:8px}.a{min-height:42px;padding:9px;border:0;border-radius:11px;background:#111827;color:#fff;font-weight:700}.l{background:#eef2f7;color:#111827}pre{display:none;white-space:pre-wrap;word-break:break-word;max-height:220px;overflow:auto;background:#0b1020;color:#dbeafe;border-radius:12px;padding:10px;font-size:11px}pre.open{display:block}.t{position:fixed;right:16px;bottom:calc(210px + env(safe-area-inset-bottom));background:#111827;color:#fff;border-radius:10px;padding:9px 12px;opacity:0;pointer-events:none;transition:.2s}.t.show{opacity:1}</style>' +
      '<button class="z" id="toggle">素材</button><section class="p" id="panel"><div class="h"><b>ZWM 社媒助手 Lite</b><span class="v">v0.1.0</span></div><div class="s"><b id="noteTitle">等待识别当前笔记…</b><div class="m" id="noteMeta"></div></div><div class="g">' +
      '<button class="a" data-a="json">复制 JSON</button><button class="a" data-a="text">复制正文</button><button class="a l" data-a="links">复制图片链接</button><button class="a l" data-a="refresh">刷新提取</button><button class="a" data-a="images">下载图片</button><button class="a" data-a="video">下载视频</button><button class="a l" data-a="preview">查看数据</button><button class="a l" data-a="close">关闭面板</button></div><pre id="preview"></pre></section><div class="t" id="toast"></div>';
    var p = s.getElementById('panel');
    s.getElementById('toggle').onclick = function(){ p.classList.toggle('open'); if (p.classList.contains('open')) data(); };
    s.addEventListener('click', function(e){ var b=e.target.closest && e.target.closest('[data-a]'); if(!b)return; var a=b.dataset.a,d=data(); if(a==='json')copy(JSON.stringify(d,null,2)); if(a==='text')copy(d.content); if(a==='links')copy(d.images.join('\n')); if(a==='refresh')toast('已重新提取'); if(a==='images')downloadImages(); if(a==='video')downloadVideo(); if(a==='preview'){var pre=s.getElementById('preview');pre.textContent=JSON.stringify(d,null,2);pre.classList.toggle('open');} if(a==='close')p.classList.remove('open'); });
  }

  function schedule(ms) { clearTimeout(timer); timer=setTimeout(function(){ lastUrl=location.href; data(); }, ms || 500); }
  function spa() { var fire=function(){window.dispatchEvent(new CustomEvent('zwm:locationchange'));}; ['pushState','replaceState'].forEach(function(n){var o=history[n];if(o.__zwm)return;var w=function(){var r=o.apply(this,arguments);fire();return r;};w.__zwm=true;history[n]=w;}); window.addEventListener('popstate',fire); window.addEventListener('zwm:locationchange',function(){schedule(700);}); }
  function observe() { if(observer||!document.body)return; observer=new MutationObserver(function(){if(location.href!==lastUrl)schedule(650);}); observer.observe(document.body,{childList:true,subtree:true}); }
  function menu() { if(typeof GM_registerMenuCommand!=='function')return; GM_registerMenuCommand('复制当前笔记 JSON',function(){copy(JSON.stringify(data(),null,2));}); GM_registerMenuCommand('复制当前笔记正文',function(){copy(data().content);}); }
  A.boot = function(){ ensure(); spa(); observe(); menu(); schedule(900); console.info('[ZWM 社媒助手 Lite] loaded v0.1.0'); };
})(globalThis);
