(function(){
'use strict';
var SOURCES={zhwikisource:{id:'zhwikisource',name:'中文维基文库',origin:'https://zh.wikisource.org',api:'https://zh.wikisource.org/w/api.php'},enwikisource:{id:'enwikisource',name:'English Wikisource',origin:'https://en.wikisource.org',api:'https://en.wikisource.org/w/api.php'}};
var state={view:'home',searchItems:[],currentBook:null,currentChapterIndex:0,previousHomeScroll:0};
var els={homeView:byId('homeView'),readerView:byId('readerView'),results:byId('results'),resultTitle:byId('resultTitle'),resultSubtitle:byId('resultSubtitle'),searchForm:byId('searchForm'),searchInput:byId('searchInput'),sourceSelect:byId('sourceSelect'),txtInput:byId('txtInput'),readerBookTitle:byId('readerBookTitle'),chapterList:byId('chapterList'),chapterTitle:byId('chapterTitle'),chapterContent:byId('chapterContent'),chapterSidebar:byId('chapterSidebar'),saveBookBtn:byId('saveBookBtn'),modalRoot:byId('modalRoot'),toast:byId('toast')};
function byId(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
function label(id){return id==='zhwikisource'?'中文维基文库':id==='enwikisource'?'English Wikisource':'本地 TXT'}
function source(id){return SOURCES[id]||null}
function key(book){return book.source+':'+book.id}
function read(keyName,fallback){try{var v=JSON.parse(localStorage.getItem(keyName));return v===null?fallback:v}catch(e){return fallback}}
function write(keyName,value){localStorage.setItem(keyName,JSON.stringify(value))}
function notify(message){els.toast.textContent=message;els.toast.classList.remove('hidden');clearTimeout(notify.t);notify.t=setTimeout(function(){els.toast.classList.add('hidden')},2200)}
function apiUrl(src,params){var url=new URL(src.api);Object.keys(params).forEach(function(k){url.searchParams.set(k,params[k])});url.searchParams.set('origin','*');return url.toString()}
async function fetchJson(url){var response=await fetch(url,{headers:{accept:'application/json'}});var data=await response.json().catch(function(){return{}});if(!response.ok||data.error)throw new Error(data.error&&data.error.info?data.error.info:'来源暂时不可用');return data}
function pages(data){var p=data&&data.query&&data.query.pages;if(!p)return[];return Array.isArray(p)?p:Object.keys(p).map(function(k){return p[k]})}
async function wikiSearch(sourceId,q){var src=source(sourceId);var data=await fetchJson(apiUrl(src,{action:'query',generator:'search',gsrsearch:q,gsrnamespace:'0',gsrlimit:'24',prop:'info',inprop:'url',format:'json',formatversion:'2'}));return pages(data).filter(function(p){return p.pageid&&p.title&&!p.missing}).map(function(p){return{id:p.pageid,title:p.title,source:src.id,url:p.fullurl||src.origin+'/?curid='+p.pageid}})}
async function wikiBook(sourceId,id){var src=source(sourceId);var info=await fetchJson(apiUrl(src,{action:'query',pageids:String(id),prop:'info',inprop:'url',format:'json',formatversion:'2'}));var page=pages(info)[0];if(!page||!page.pageid||page.missing)throw new Error('作品不存在');var sub=await fetchJson(apiUrl(src,{action:'query',generator:'allpages',gapprefix:page.title+'/',gapnamespace:'0',gaplimit:'max',prop:'info',inprop:'url',format:'json',formatversion:'2'})).catch(function(){return{query:{pages:[]}}});var chapters=pages(sub).filter(function(p){return p.pageid&&p.title&&!p.missing}).map(function(p){return{id:p.pageid,title:p.title.indexOf(page.title+'/')===0?p.title.slice(page.title.length+1):p.title,source:src.id,url:p.fullurl||src.origin+'/?curid='+p.pageid}}).sort(function(a,b){return a.title.localeCompare(b.title,undefined,{numeric:true,sensitivity:'base'})});if(!chapters.length)chapters=[{id:page.pageid,title:page.title,source:src.id,url:page.fullurl||src.origin+'/?curid='+page.pageid}];return{id:page.pageid,title:page.title,source:src.id,sourceName:src.name,url:page.fullurl||src.origin+'/?curid='+page.pageid,chapters:chapters}}
function cleanWikiHtml(raw,src){var doc=new DOMParser().parseFromString('<div id="owl-root">'+raw+'</div>','text/html');doc.querySelectorAll('script,style,iframe,object,embed,form,input,button,textarea,select,.mw-editsection,.noprint,.navbox,.metadata,.ambox,.sistersitebox').forEach(function(node){node.remove()});doc.querySelectorAll('*').forEach(function(node){Array.from(node.attributes).forEach(function(attr){if(/^on/i.test(attr.name)||/javascript:/i.test(attr.value))node.removeAttribute(attr.name)})});doc.querySelectorAll('a').forEach(function(a){var href=a.getAttribute('href')||'';if(href.indexOf('/wiki/')===0)a.href=src.origin+href;a.target='_blank';a.rel='noopener noreferrer'});doc.querySelectorAll('img').forEach(function(img){var value=img.getAttribute('src')||'';if(value.indexOf('//')===0)img.src='https:'+value;else if(value.indexOf('/')===0)img.src=src.origin+value;img.loading='lazy'});var root=doc.getElementById('owl-root');return root?root.innerHTML:''}
async function wikiChapter(sourceId,id){var src=source(sourceId);var data=await fetchJson(apiUrl(src,{action:'parse',pageid:String(id),prop:'text|displaytitle',disableeditsection:'1',redirects:'1',format:'json',formatversion:'2'}));if(!data.parse||!data.parse.text)throw new Error('章节内容为空');var title=(data.parse.displaytitle||data.parse.title||'未命名').replace(/<[^>]+>/g,'').trim();return{title:title,content:cleanWikiHtml(data.parse.text,src)}}
function busy(message){els.results.innerHTML='<div class="empty"><span class="loading"><span class="spinner"></span>'+esc(message)+'</span></div>'}
function renderResults(items){state.searchItems=items;if(!items.length){els.results.innerHTML='<div class="empty">没有找到结果，可以换一个关键词或切换来源。</div>';return}els.results.innerHTML=items.map(function(item,i){return'<article class="result-card"><div class="meta">'+esc(label(item.source))+'</div><h3>'+esc(item.title)+'</h3><div class="card-actions"><button class="primary-btn" data-open-index="'+i+'">打开目录</button><a class="soft-btn" href="'+esc(item.url)+'" target="_blank" rel="noopener noreferrer" style="text-decoration:none">原始页</a></div></article>'}).join('')}
async function doSearch(event){event.preventDefault();var q=els.searchInput.value.trim();if(!q)return;els.resultTitle.textContent='搜索中';els.resultSubtitle.textContent='正在连接公开内容来源';busy('正在搜索“'+q+'”');try{var items=await wikiSearch(els.sourceSelect.value,q);els.resultTitle.textContent='搜索结果';els.resultSubtitle.textContent='共找到 '+items.length+' 条公开内容';renderResults(items)}catch(error){els.resultTitle.textContent='搜索失败';els.resultSubtitle.textContent=error.message;els.results.innerHTML='<div class="empty">'+esc(error.message)+'。部分地区网络可能无法直连维基文库。</div>'}}
async function openSearchItem(index){var item=state.searchItems[index];if(!item)return;state.previousHomeScroll=window.scrollY;els.resultTitle.textContent='正在整理目录';busy('正在读取作品结构');try{await openBook(await wikiBook(item.source,item.id),0)}catch(error){notify(error.message)}}
function showReader(){state.view='reader';els.homeView.classList.add('hidden');els.readerView.classList.remove('hidden');window.scrollTo(0,0)}
function showHome(){state.view='home';els.readerView.classList.add('hidden');els.homeView.classList.remove('hidden');els.chapterSidebar.classList.remove('open');window.scrollTo(0,state.previousHomeScroll||0)}
function renderChapterList(){var book=state.currentBook;if(!book)return;els.chapterList.innerHTML=book.chapters.map(function(chapter,i){return'<button class="chapter-item '+(i===state.currentChapterIndex?'active':'')+'" data-chapter-index="'+i+'">'+esc(chapter.title)+'</button>'}).join('');var active=els.chapterList.querySelector('.active');if(active)active.scrollIntoView({block:'nearest'})}
function books(){return read('owlreader.books',[])}
function saved(book){return books().some(function(item){return key(item)===key(book)})}
function refreshSave(){if(state.currentBook)els.saveBookBtn.textContent=saved(state.currentBook)?'★ 已收藏':'☆ 收藏'}
function toggleSave(){var book=state.currentBook;if(!book)return;var list=books();var idx=list.findIndex(function(item){return key(item)===key(book)});if(idx>=0){list.splice(idx,1);notify('已从书架移除')}else{list.unshift({id:book.id,title:book.title,source:book.source,sourceName:book.sourceName,url:book.url,chapters:book.chapters,addedAt:Date.now()});notify('已加入书架')}write('owlreader.books',list);refreshSave()}
async function openBook(book,index){state.currentBook=book;state.currentChapterIndex=Math.max(0,Math.min(index||0,book.chapters.length-1));els.readerBookTitle.textContent=book.title;showReader();renderChapterList();refreshSave();await loadChapter(state.currentChapterIndex)}
async function loadChapter(index){var book=state.currentBook;if(!book||!book.chapters[index])return;state.currentChapterIndex=index;renderChapterList();els.chapterSidebar.classList.remove('open');els.chapterTitle.textContent='正在加载';els.chapterContent.innerHTML='<div class="empty"><span class="loading"><span class="spinner"></span>正在获取内容</span></div>';byId('prevChapterBtn').disabled=index<=0;byId('nextChapterBtn').disabled=index>=book.chapters.length-1;window.scrollTo(0,0);var chapter=book.chapters[index];try{var title,content;if(book.source==='local'){var stored=await idbGet('localBooks',String(book.id));if(!stored)throw new Error('本地文件已被清理');title=stored.chapters[index].title;content='<p>'+stored.chapters[index].content.split(/\n+/).map(esc).join('</p><p>')+'</p>'}else{var data=await wikiChapter(book.source,chapter.id);title=data.title;content=data.content}els.chapterTitle.textContent=title||chapter.title;els.chapterContent.innerHTML=content;write('owlreader.progress.'+key(book),{index:index,chapterId:chapter.id,updatedAt:Date.now()});refreshSave()}catch(error){els.chapterTitle.textContent='加载失败';els.chapterContent.innerHTML='<div class="empty">'+esc(error.message)+'<br><br><button class="primary-btn" id="retryBtn">重试</button></div>';var retry=byId('retryBtn');if(retry)retry.onclick=function(){loadChapter(index)}}}
function closeModal(){els.modalRoot.innerHTML=''}
function renderBookshelf(){var list=books();var html='<div class="modal-backdrop" data-close-modal><section class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>我的书架</h2><button class="modal-close" data-close-modal>×</button></div><div class="book-list">';if(!list.length)html+='<div class="empty">书架还是空的。搜索作品或导入 TXT 后，点击“收藏”。</div>';else html+=list.map(function(book,i){var progress=read('owlreader.progress.'+key(book),{index:0});return'<div class="book-row"><div class="book-row-info"><strong>'+esc(book.title)+'</strong><span>'+esc(label(book.source))+' · '+esc((book.chapters[progress.index]||book.chapters[0]||{}).title||'未开始')+'</span></div><button class="primary-btn" data-open-book="'+i+'">继续</button><button class="soft-btn" data-remove-book="'+i+'">移除</button></div>'}).join('');html+='</div></section></div>';els.modalRoot.innerHTML=html}
function removeBook(index){var list=books();if(!list[index])return;list.splice(index,1);write('owlreader.books',list);renderBookshelf();refreshSave()}
async function openSaved(index){var book=books()[index];if(!book)return;closeModal();var progress=read('owlreader.progress.'+key(book),{index:0});try{if(book.source==='local')await openBook(book,progress.index||0);else await openBook(await wikiBook(book.source,book.id),progress.index||0)}catch(error){notify(error.message)}}
function settings(){return Object.assign({theme:'sepia',fontSize:20,lineHeight:1.9,width:760},read('owlreader.settings',{}))}
function applySettings(s){write('owlreader.settings',s);document.body.classList.remove('theme-light','theme-sepia','theme-dark');document.body.classList.add('theme-'+s.theme);document.documentElement.style.setProperty('--reader-size',s.fontSize+'px');document.documentElement.style.setProperty('--reader-line',String(s.lineHeight));document.documentElement.style.setProperty('--reader-width',s.width+'px')}
function renderSettings(){var s=settings();els.modalRoot.innerHTML='<div class="modal-backdrop" data-close-modal><section class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>阅读设置</h2><button class="modal-close" data-close-modal>×</button></div><div class="setting-row"><strong>主题</strong><div class="theme-pills"><button class="theme-pill '+(s.theme==='light'?'active':'')+'" data-theme="light">浅色</button><button class="theme-pill '+(s.theme==='sepia'?'active':'')+'" data-theme="sepia">米黄</button><button class="theme-pill '+(s.theme==='dark'?'active':'')+'" data-theme="dark">深色</button></div><span></span></div><div class="setting-row"><strong>字号</strong><input id="fontSizeRange" type="range" min="15" max="32" value="'+s.fontSize+'"><span id="fontSizeValue">'+s.fontSize+'px</span></div><div class="setting-row"><strong>行距</strong><input id="lineHeightRange" type="range" min="1.4" max="2.6" step="0.1" value="'+s.lineHeight+'"><span id="lineHeightValue">'+s.lineHeight+'</span></div><div class="setting-row"><strong>阅读宽度</strong><input id="widthRange" type="range" min="560" max="1000" step="20" value="'+s.width+'"><span id="widthValue">'+s.width+'px</span></div></section></div>'}
function renderRules(){var custom=read('owlreader.customRules',[]);var html='<div class="modal-backdrop" data-close-modal><section class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><h2>规则中心</h2><div class="meta">内置来源经过审核；外部规则只保存为待审核。</div></div><button class="modal-close" data-close-modal>×</button></div><div class="source-card"><strong>中文维基文库</strong><span>MediaWiki API · 已审核 · CC BY-SA / 公版</span></div><div class="source-card"><strong>English Wikisource</strong><span>MediaWiki API · 已审核 · CC BY-SA / Public domain</span></div><div class="source-card"><strong>本地 TXT</strong><span>浏览器本地解析 · 不上传</span></div><div class="import-card"><input id="ruleInput" type="file" accept="application/json,.json"><label for="ruleInput">＋ 导入规则 JSON</label><small>只保存为待审核，不执行远程脚本</small></div>';if(custom.length)html+='<h3>待审核规则</h3>'+custom.map(function(r){return'<div class="source-card"><strong>'+esc(r.name||r.id||'未命名规则')+'</strong><span>'+esc(r.homepage||'无主页')+' · '+esc(r.license||'未声明许可')+'</span></div>'}).join('');html+='</section></div>';els.modalRoot.innerHTML=html}
function validateRule(rule){['version','id','name','homepage','license','sourceType'].forEach(function(k){if(!rule||!rule[k])throw new Error('缺少字段：'+k)});var u=new URL(rule.homepage);if(u.protocol!=='https:')throw new Error('主页必须使用 HTTPS');if(['mediawiki','opds','static-catalog'].indexOf(rule.sourceType)<0)throw new Error('不支持的 sourceType')}
async function importRule(file){try{var rule=JSON.parse(await file.text());validateRule(rule);var rules=read('owlreader.customRules',[]);rule.reviewStatus='pending';rule.importedAt=Date.now();rules.unshift(rule);write('owlreader.customRules',rules);notify('规则已保存为待审核');renderRules()}catch(error){notify('规则导入失败：'+error.message)}}
function splitTxt(text,title,id){var lines=text.replace(/^\uFEFF/,'').split(/\r?\n/);var heading=/^\s*(第[0-9一二三四五六七八九十百千万零〇两]+[章回卷节部篇][^\n]{0,60}|Chapter\s+[0-9IVXLCDM]+[^\n]{0,60})\s*$/i;var chapters=[],current={title:'正文',content:[]};lines.forEach(function(line){if(heading.test(line.trim())){if(current.content.join('').trim())chapters.push({title:current.title,content:current.content.join('\n')});current={title:line.trim(),content:[]}}else current.content.push(line)});if(current.content.join('').trim())chapters.push({title:current.title,content:current.content.join('\n')});if(!chapters.length)chapters=[{title:title,content:text}];return{id:id,title:title,chapters:chapters}}
async function importTxt(file){if(!file)return;if(file.size>12*1024*1024){notify('TXT 暂时限制在 12MB 以内');return}try{var text=await file.text();var id=crypto.randomUUID();var title=file.name.replace(/\.txt$/i,'');var stored=splitTxt(text,title,id);await idbPut('localBooks',id,stored);var book={id:id,title:title,source:'local',sourceName:'本地 TXT',url:'',chapters:stored.chapters.map(function(chapter,i){return{id:id+':'+i,title:chapter.title,source:'local',url:''}})};var list=books().filter(function(item){return key(item)!==key(book)});list.unshift(book);write('owlreader.books',list);notify('已导入 '+stored.chapters.length+' 个章节');await openBook(book,0)}catch(error){notify('导入失败：'+error.message)}finally{els.txtInput.value=''}}
function openDb(){return new Promise(function(resolve,reject){var req=indexedDB.open('owlreader',1);req.onupgradeneeded=function(){if(!req.result.objectStoreNames.contains('localBooks'))req.result.createObjectStore('localBooks')};req.onsuccess=function(){resolve(req.result)};req.onerror=function(){reject(req.error)}})}
async function idbPut(store,keyName,value){var db=await openDb();return new Promise(function(resolve,reject){var tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value,keyName);tx.oncomplete=function(){db.close();resolve()};tx.onerror=function(){db.close();reject(tx.error)}})}
async function idbGet(store,keyName){var db=await openDb();return new Promise(function(resolve,reject){var tx=db.transaction(store,'readonly');var req=tx.objectStore(store).get(keyName);req.onsuccess=function(){db.close();resolve(req.result)};req.onerror=function(){db.close();reject(req.error)}})}
els.searchForm.addEventListener('submit',doSearch);els.results.addEventListener('click',function(e){var b=e.target.closest('[data-open-index]');if(b)openSearchItem(Number(b.dataset.openIndex))});els.chapterList.addEventListener('click',function(e){var b=e.target.closest('[data-chapter-index]');if(b)loadChapter(Number(b.dataset.chapterIndex))});byId('homeBtn').onclick=showHome;byId('readerBackBtn').onclick=showHome;byId('bookshelfBtn').onclick=renderBookshelf;byId('rulesBtn').onclick=renderRules;byId('settingsBtn').onclick=renderSettings;byId('chapterDrawerBtn').onclick=function(){els.chapterSidebar.classList.toggle('open')};els.saveBookBtn.onclick=toggleSave;byId('prevChapterBtn').onclick=function(){loadChapter(state.currentChapterIndex-1)};byId('nextChapterBtn').onclick=function(){loadChapter(state.currentChapterIndex+1)};els.txtInput.onchange=function(){importTxt(els.txtInput.files[0])};
els.modalRoot.addEventListener('click',function(e){if(e.target.matches('[data-close-modal]'))closeModal();var open=e.target.closest('[data-open-book]');if(open)openSaved(Number(open.dataset.openBook));var remove=e.target.closest('[data-remove-book]');if(remove)removeBook(Number(remove.dataset.removeBook));var theme=e.target.closest('[data-theme]');if(theme){var s=settings();s.theme=theme.dataset.theme;applySettings(s);renderSettings()}});els.modalRoot.addEventListener('input',function(e){var s=settings();if(e.target.id==='fontSizeRange'){s.fontSize=Number(e.target.value);byId('fontSizeValue').textContent=s.fontSize+'px'}if(e.target.id==='lineHeightRange'){s.lineHeight=Number(e.target.value);byId('lineHeightValue').textContent=s.lineHeight}if(e.target.id==='widthRange'){s.width=Number(e.target.value);byId('widthValue').textContent=s.width+'px'}applySettings(s)});els.modalRoot.addEventListener('change',function(e){if(e.target.id==='ruleInput'&&e.target.files[0])importRule(e.target.files[0])});document.addEventListener('keydown',function(e){if(state.view!=='reader'||els.modalRoot.innerHTML)return;if(e.key==='ArrowLeft'&&state.currentChapterIndex>0)loadChapter(state.currentChapterIndex-1);if(e.key==='ArrowRight'&&state.currentBook&&state.currentChapterIndex<state.currentBook.chapters.length-1)loadChapter(state.currentChapterIndex+1);if(e.key==='Escape')els.chapterSidebar.classList.remove('open')});applySettings(settings());if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(function(){});
})();
