(()=>{
const seed=window.PLATFORM_SEED||{};
const generated=window.PLATFORM_GENERATED||{platforms:{},diagnostics:{}};
const boardMode={};
const boardSort={};
const COPY_SORTS=[['hot','综合'],['aum','带单规模'],['followers','跟单人数'],['days','带单天数'],['pnl','收益额'],['roi','收益率'],['mdd','低回撤'],['winRate','胜率'],['followerPnl','跟单收益']];
const TRADER_SORTS=[['pnl','收益额'],['roi','收益率'],['winRate','胜率'],['mdd','低回撤'],['volume','交易量'],['trades','交易次数'],['assets','资产']];
const FIELD_LABEL={aum:'带单规模',followers:'当前跟单',days:'带单天数',pnl:'收益额',roi:'收益率',mdd:'最大回撤',winRate:'胜率',followerPnl:'跟单收益',volume:'交易量',trades:'交易次数',assets:'资产',sharpe:'夏普率',profitShare:'分润',wallet:'钱包',score:'评分'};
function n(v){const x=Number(v);return Number.isFinite(x)?x:null}
function fmtMoney(v){const x=n(v);if(x===null)return'—';const s=x<0?'-':'+';const a=Math.abs(x);if(a>=1e9)return`${s}$${(a/1e9).toFixed(2)}B`;if(a>=1e6)return`${s}$${(a/1e6).toFixed(2)}M`;if(a>=1e3)return`${s}$${(a/1e3).toFixed(1)}K`;return`${s}$${a.toLocaleString('en-US',{maximumFractionDigits:2})}`}
function fmtPlainMoney(v){const x=n(v);if(x===null)return'—';const a=Math.abs(x);if(a>=1e9)return`$${(x/1e9).toFixed(2)}B`;if(a>=1e6)return`$${(x/1e6).toFixed(2)}M`;if(a>=1e3)return`$${(x/1e3).toFixed(1)}K`;return`$${x.toLocaleString('en-US',{maximumFractionDigits:2})}`}
function fmtPct(v){const x=n(v);return x===null?'—':`${x>=0?'+':''}${x.toFixed(2)}%`}
function fmtNum(v){const x=n(v);return x===null?'—':Math.round(x).toLocaleString('en-US')}
function metricText(key,v){if(['roi','mdd','winRate'].includes(key))return fmtPct(v);if(['pnl','followerPnl'].includes(key))return fmtMoney(v);if(['aum','assets','volume'].includes(key))return fmtPlainMoney(v);if(key==='days')return`${fmtNum(v)}天`;if(key==='profitShare')return fmtPct(v);return fmtNum(v)}
function metricNumber(u,key){return n(u?.metrics?.[key])}
function hasMetric(users,key){return users.some(u=>metricNumber(u,key)!==null)}
function compositeCompare(a,b){for(const k of ['aum','followers','days']){const A=metricNumber(a,k)||0,B=metricNumber(b,k)||0;if(A!==B)return B-A}return 0}
function sortUsers(users,key){const out=[...users];if(key==='hot')return out.sort(compositeCompare);if(key==='mdd')return out.sort((a,b)=>{const A=metricNumber(a,key),B=metricNumber(b,key);if(A===null)return 1;if(B===null)return-1;return A-B});return out.sort((a,b)=>{const A=metricNumber(a,key),B=metricNumber(b,key);if(A===null)return 1;if(B===null)return-1;return B-A})}
function generatedBoard(key,mode){const b=generated?.platforms?.[key]?.[mode];return b&&Array.isArray(b.users)&&b.users.length?b:null}
function boardFor(key,mode){const live=generatedBoard(key,mode),fallback=seed?.[key]?.[mode]||{users:[]};if(!live)return{...fallback,users:[],_origin:'empty',sourceUrl:fallback.sourceUrl,note:fallback.note||'当前没有可验证的公开用户快照，不展示静态种子用户。'};return{...fallback,...live,users:live.users,_origin:'live',sourceUrl:live.sourceUrl||fallback.sourceUrl}}
function statusFor(board,key,mode){if(board._origin==='live')return`<span class="sync-badge">● 自动同步 · ${esc(board.generatedAt||generated.generatedAt||'最新')}</span>`;const diag=generated?.diagnostics?.[`${key}:${mode}`];if((board.users||[]).length)return`<span class="sync-badge seed">◐ 最近可验证快照${diag?.error?' · 实时抓取暂时失败':''}</span>`;return`<span class="sync-badge empty">○ 等待公开运行态数据${diag?.error?' · 本轮抓取未取到用户':''}</span>`}
function primaryFor(u,sort){const m=u.metrics||{};let key=sort;if(sort==='hot'){if(n(m.aum)!==null)key='aum';else if(n(m.followers)!==null)key='followers';else if(n(m.days)!==null)key='days';else if(n(m.pnl)!==null)key='pnl';else key='roi'}return{key,label:sort==='hot'?`综合 · ${FIELD_LABEL[key]||key}`:(FIELD_LABEL[key]||key),value:metricText(key,m[key])}}
function metricPairs(u){const order=['aum','followers','days','pnl','roi','mdd','winRate','followerPnl','assets','volume','trades','sharpe','profitShare'];return order.filter(k=>metricNumber(u,k)!==null).map(k=>[FIELD_LABEL[k]||k,metricText(k,u.metrics[k]),k])}
function avatarHtml(u){if(u.avatarUrl)return`<span class="pu-avatar"><img src="${esc(u.avatarUrl)}" alt="" loading="lazy" onerror="this.parentNode.textContent='${esc((u.name||'?').slice(0,1))}'"></span>`;return`<span class="pu-avatar">${esc((u.name||'?').slice(0,1))}</span>`}
function cardHtml(u,i,sort,board,key,mode){const p=primaryFor(u,sort),pairs=metricPairs(u),exact=!!u.profileUrl;return`<article class="platform-user-v2 card" data-pv2-user="${i}"><div class="pu-rank ${i<3?'top':''}">${i+1}</div><div class="pu-ident">${avatarHtml(u)}<div class="pu-namebox"><div class="pu-name">${esc(u.name||u.addressLabel||'未命名交易员')}</div><div class="pu-badges">${u.badge?`<span class="pu-badge">${esc(u.badge)}</span>`:''}${exact?'<span class="pu-badge">主页可直达</span>':''}</div><div class="fresh-row"><span>${esc(board.period||'当前')}</span>${u.wallet?`<span>${esc(u.wallet)}</span>`:''}</div></div></div><div class="pu-main"><div class="pu-mainlabel">${esc(p.label)}</div><div class="pu-mainvalue ${String(p.value).startsWith('-')?'neg':''}">${esc(p.value)}</div><div class="pu-sub">${pairs.slice(0,5).map(([a,b])=>`<span>${esc(a)} <b>${esc(b)}</b></span>`).join('')}</div></div><div class="pu-side">${pairs.slice(0,4).map(([a,b])=>`<div><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}</div><div class="pu-actions"><button type="button" data-pv2-detail="${i}">详情</button>${exact?`<a class="primary" href="${esc(u.profileUrl)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">用户主页 ↗</a>`:''}</div></article>`}
function ensureDrawer(){if(document.getElementById('profileDrawerV2'))return;document.body.insertAdjacentHTML('beforeend','<div class="drawer-mask-v2" id="drawerMaskV2"></div><aside class="profile-drawer-v2" id="profileDrawerV2"><button class="pd-close" id="pdCloseV2">×</button><div id="pdContentV2"></div></aside>');const close=()=>{$('#drawerMaskV2').classList.remove('open');$('#profileDrawerV2').classList.remove('open')};$('#drawerMaskV2').onclick=close;$('#pdCloseV2').onclick=close}
function openDetail(u,board,key,mode){ensureDrawer();const pairs=metricPairs(u);$('#pdContentV2').innerHTML=`<span class="pd-platform">${esc((PLATFORM_INFO[key]?.name||key).toUpperCase())} · ${mode==='copy'?'带单榜':'交易员榜'}</span><h2>${esc(u.name||u.addressLabel||'交易员')}</h2>${u.badge?`<span class="pu-badge">${esc(u.badge)}</span>`:''}<div class="pd-grid">${pairs.map(([a,b])=>`<div class="pd-metric"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}</div><div class="pd-note">数据状态：${board._origin==='live'?'自动同步':'最近可验证快照'}。${esc(u.note||board.note||'站内展示公开交易表现，不构成投资建议。')}</div><div class="pd-links">${u.profileUrl?`<a class="source-btn" href="${esc(u.profileUrl)}" target="_blank" rel="noopener">打开用户主页 ↗</a>`:''}${board.sourceUrl?`<a class="source-btn secondary" href="${esc(board.sourceUrl)}" target="_blank" rel="noopener">核对官方榜 ↗</a>`:''}</div>`;$('#drawerMaskV2').classList.add('open');$('#profileDrawerV2').classList.add('open')}
function availableSorts(mode,users){const base=mode==='copy'?COPY_SORTS:TRADER_SORTS;return base.filter(([k])=>k==='hot'||hasMetric(users,k))}
function renderBoard(key,mode){const info=PLATFORM_INFO[key],board=boardFor(key,mode),users=board.users||[];const sorts=availableSorts(mode,users);if(!boardSort[`${key}:${mode}`]||!sorts.some(([k])=>k===boardSort[`${key}:${mode}`]))boardSort[`${key}:${mode}`]=sorts[0]?.[0]||(mode==='copy'?'hot':'pnl');const sort=boardSort[`${key}:${mode}`];const ordered=sortUsers(users,sort);const diag=generated?.diagnostics?.[`${key}:${mode}`];const body=$('#platformBody');let html=`<section class="platform-radar-body"><div class="platform-radar-head"><div><span class="label">${mode==='copy'?'LEAD / COPY TRADERS':'TRADER LEADERBOARD'}</span><h2>${esc(board.title||`${info.name} ${mode==='copy'?'带单榜':'交易员榜'}`)}</h2></div><p>${statusFor(board,key,mode)}<br>${ordered.length?`站内已有 ${ordered.length} 个具体用户`:'本轮没有可验证用户行'}</p></div>`;
 if(sorts.length>1)html+=`<div class="platform-filterbar card">${sorts.map(([k,t])=>`<button class="pf-btn ${k===sort?'active':''}" data-pv2-sort="${k}">${t}</button>`).join('')}</div>`;
 if(ordered.length){html+=`<div class="platform-mini-summary"><div class="pms card"><span>具体用户</span><b>${ordered.length}</b></div><div class="pms card"><span>当前排序</span><b>${esc((sorts.find(x=>x[0]===sort)||[])[1]||sort)}</b></div><div class="pms card"><span>数据来源</span><b>${board._origin==='live'?'自动同步':'可验证快照'}</b></div><div class="pms card"><span>用户主页</span><b>${ordered.filter(x=>x.profileUrl).length} 可直达</b></div></div><div class="platform-user-list-v2">${ordered.map((u,i)=>cardHtml(u,i,sort,board,key,mode)).join('')}</div>`}
 else html+=`<article class="platform-empty-v2 card"><div><h3>这里不再放“大段说明占位”</h3><p>${esc(board.note||'自动同步器正在尝试从公开运行态抓取具体用户；没有可靠用户数据时保持空，不生成假账号。')}${diag?.error?` 最近错误：${esc(String(diag.error).slice(0,180))}`:''}</p></div>${board.sourceUrl?`<a class="source-btn secondary" href="${esc(board.sourceUrl)}" target="_blank" rel="noopener">官方榜 ↗</a>`:''}</article>`;
 html+='</section>';body.innerHTML=html;body.querySelectorAll('[data-pv2-sort]').forEach(b=>b.onclick=()=>{boardSort[`${key}:${mode}`]=b.dataset.pv2Sort;renderBoard(key,mode)});body.querySelectorAll('[data-pv2-user]').forEach(el=>{const u=ordered[Number(el.dataset.pv2User)];el.onclick=e=>{if(e.target.closest('a'))return;openDetail(u,board,key,mode)}});body.querySelectorAll('[data-pv2-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();openDetail(ordered[Number(b.dataset.pv2Detail)],board,key,mode)})}
function renderOverview(key){const info=PLATFORM_INFO[key],copy=boardFor(key,'copy'),trader=boardFor(key,'trader');$('#platformBody').innerHTML=`<article class="platform-block card"><span class="label">PLATFORM OVERVIEW</span><h2>${esc(info.name)} 当前雷达</h2><p>${esc(info.summary)}</p><div class="fact-grid"><div class="fact"><span>用户规模</span><b>${esc(info.users)}</b></div><div class="fact"><span>带单用户</span><b>${(copy.users||[]).length}</b></div><div class="fact"><span>交易员用户</span><b>${(trader.users||[]).length}</b></div><div class="fact"><span>同步时间</span><b>${esc(generated.generatedAt||seed.capturedAt||'—')}</b></div></div></article><article class="platform-block card"><span class="label">PUBLIC METRICS</span><h2>已纳入字段</h2><div class="chips">${(info.metrics||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div class="source-btns">${(info.links||[]).slice(0,3).map(([n,u],i)=>`<a class="source-btn ${i?'secondary':''}" href="${esc(u)}" target="_blank" rel="noopener">${esc(n)} ↗</a>`).join('')}</div></article>`}
renderPlatform=function(key){const info=PLATFORM_INFO[key],x=EX.find(v=>v.key===key);if(!info||!x)return;if(!boardMode[key])boardMode[key]='copy';const mode=boardMode[key];$('#platformHead').innerHTML=`<div class="platform-head-row"><div><span class="label">${esc(info.tag)}</span><h1>${esc(info.name)} 雷达</h1><p>${esc(info.summary)}</p><span class="integrate live">具体用户优先在本站展示 · 自动同步失败则保留最后可验证快照</span></div><div class="platform-user"><span>公开用户规模</span><strong>${esc(info.users)}</strong></div></div>`;$('#platformSubnav').innerHTML=`<button class="platform-subtab ${mode==='copy'?'active':''}" data-pv2-mode="copy">带单榜</button><button class="platform-subtab ${mode==='trader'?'active':''}" data-pv2-mode="trader">交易员榜</button><button class="platform-subtab ${mode==='overview'?'active':''}" data-pv2-mode="overview">平台概览</button>`;$('#platformSubnav').querySelectorAll('[data-pv2-mode]').forEach(b=>b.onclick=()=>{boardMode[key]=b.dataset.pv2Mode;renderPlatform(key)});if(mode==='overview')renderOverview(key);else renderBoard(key,mode)};
ensureDrawer();
window.__PLATFORM_RADAR_V2__={boardFor,sortUsers,COPY_SORTS,TRADER_SORTS};
})();
